inherit_from:
  - https://raw.githubusercontent.com/cookpad/guides/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*
    - vendor/**/.*

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Rails/RakeEnvironment:
  Enabled: false
Rails/EnvironmentVariableAccess:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
